### PR TITLE
Fix captions cut-off on mobile

### PR DESCRIPTION
**Pull request by MarquisLP**

### CODE REVIEW

**Review by Jevan5 — CHANGES_REQUESTED** [review]
On browsers, the width should be 50% of the width of the container, with a minimum of 250px.

In mobile, the width could be 100% of the width of the container, to compensate for smaller screens.

This has to be done conditionally on the user agent, because this change is currently breaking the design by affecting browsers as well.

**Comment by rschick** [comment]
Please use CSS media selector based on screen size and not user agent detection.

**Comment by MarquisLP** [comment]
I set the minimum width of the CSS selector to `767px` to account for landscape mode as well. But we can tweak that number if needed.

**Review by Jevan5 — APPROVED** [review]
Worked in my local instance

**Pull request merged**
